# src/config.py
from .settings import settings

# --- Scanner Model Configuration ---
SCANNER_LLM_PROVIDER = settings.SCANNER_LLM_PROVIDER
SCANNER_LLAMA_CPP_MODEL_PATH = settings.SCANNER_LLAMA_CPP_MODEL_PATH
SCANNER_OLLAMA_MODEL = settings.SCANNER_OLLAMA_MODEL
SCANNER_OLLAMA_URL = settings.SCANNER_OLLAMA_URL
SCANNER_GEMINI_MODEL = settings.SCANNER_GEMINI_MODEL

# --- Patcher Model Configuration ---
PATCHER_LLM_PROVIDER = settings.PATCHER_LLM_PROVIDER
PATCHER_LLAMA_CPP_MODEL_PATH = settings.PATCHER_LLAMA_CPP_MODEL_PATH
PATCHER_OLLAMA_MODEL = settings.PATCHER_OLLAMA_MODEL
PATCHER_OLLAMA_URL = settings.PATCHER_OLLAMA_URL
PATCHER_GEMINI_MODEL = settings.PATCHER_GEMINI_MODEL

# --- LLM Timeout ---
LLM_TIMEOUT = settings.LLM_TIMEOUT

# --- Database Configuration ---
DATABASE_URL = settings.DATABASE_URL

# --- Tool Paths ---
GITLEAKS_PATH = settings.GITLEAKS_PATH
SEMGREP_PATH = settings.SEMGREP_PATH
BANDIT_PATH = settings.BANDIT_PATH
BRAKEMAN_PATH = settings.BRAKEMAN_PATH
NJSSCAN_PATH = settings.NJSSCAN_PATH
GOSEC_PATH = settings.GOSEC_PATH
CPPCHECK_PATH = settings.CPPCHECK_PATH
RUBYCRITIC_PATH = settings.RUBYCRITIC_PATH
NODE_QUALITY_TOOL_PATH = settings.NODE_QUALITY_TOOL_PATH
GOCYCLO_PATH = settings.GOCYCLO_PATH
RUST_QUALITY_TOOL_PATH = settings.RUST_QUALITY_TOOL_PATH
CPP_QUALITY_TOOL_PATH = settings.CPP_QUALITY_TOOL_PATH
SAST_GLOBAL_EXCLUSIONS = settings.SAST_GLOBAL_EXCLUSIONS
GENERATE_TEST_SCRIPT_DEFAULT = settings.GENERATE_TEST_SCRIPT_DEFAULT
DOCKER_REGISTRY = settings.DOCKER_REGISTRY
RUN_TESTS_IN_CONTAINER_DEFAULT = settings.RUN_TESTS_IN_CONTAINER_DEFAULT
TEST_CONTAINER_IMAGES = settings.TEST_CONTAINER_IMAGES